resources:
- ../../stable/rbac
- rbac_add_snapshotter.yaml
- rbac_add_resizer.yaml
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: external-provisioner-role
  path: rbac_add_snapshots_to_provisioner.yaml
