apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-gce-pd-controller
spec:
  template:
    spec:
      containers:
      - name: gce-pd-node-labeler
        image: cloud-provider-gcp/gce-pd-node-labeler
        args:
          - "--v=5"
          - "--configmap-name=machine-pd-compatibility"
          - "--configmap-namespace=gce-pd-csi-driver"
          - "--http-endpoint=:22015"
        ports:
          - containerPort: 22015
            name: http-endpoint
            protocol: TCP
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz/node-labeler
            port: http-endpoint
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
