include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.20
  script:
    - cd pkg && go test ./... -v

build-docker-image:
  variables:
    EXTRA_ARGS: "--build-arg=BUILDPLATFORM=linux --build-arg=STAGINGVERSION=$CI_COMMIT_TAG"
  extends: .build-docker-image
