kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-controller
spec:
  template:
    spec:
      containers:
        - name: csi-resizer
          imagePullPolicy: Always
          image: gke.gcr.io/csi-resizer:v0.2.0-gke.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--leader-election"
            - --leader-election-namespace=$(PDCSI_NAMESPACE)
          env:
          - name: PDCSI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
