apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gce-pd-csi-driver
resources:
- ../../base/
patchesStrategicMerge:
- controller_readonly.yaml
transformers:
- ../../images/alpha
