apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  gce-pd-csi-driver
resources:
- ../../base/
patchesStrategicMerge:
- no-node-driver-registrar-probe.yaml
transformers:
- ../../images/stable-1-19
