apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: csi-gce-pd-node-psp-win
spec:
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - '*'
  hostNetwork: true
  allowedHostPaths:
  - pathPrefix: \var\lib\kubelet
  - pathPrefix: \var\lib\kubelet\plugins_registry
  - pathPrefix: \var\lib\kubelet\plugins\pd.csi.storage.gke.io
  - pathPrefix: \\.\pipe\csi-proxy-disk-v1beta1
  - pathPrefix: \\.\pipe\csi-proxy-volume-v1beta1
  - pathPrefix: \\.\pipe\csi-proxy-filesystem-v1alpha1

