apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../alpha
patches:
- controller_always_pull.yaml
- node_always_pull.yaml
images:
# Replace this with your private image names and tags
- name: REPLACEME/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/REPLACEME/gcp-compute-persistent-disk-csi-driver
  newTag: "latest"
