apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- controller_always_pull.yaml
- node_always_pull.yaml
- windows_hostprocess.yaml
namespace: gce-pd-csi-driver
resources:
- ../../base/
# Here dev overlay is using the same image as alpha
transformers:
- ../../images/stable-master
# To change the dev image, add something like the following.
#images:
#- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
#  newName: gcr.io/mattcary-gke-dev-owned/csi/gce-pd-driver
#  newTag: latest
