kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      containers:
        - name: gce-pd-driver
          imagePullPolicy: Always
          image: gcr.io/dyzz-csi-staging/csi/gce-pd-driver:latest
        - name: csi-driver-registrar
          image: gcr.io/gke-release/csi-driver-registrar:v0.4.1-gke.0