apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pd-csi-taint-webhook-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pd-csi-taint-webhook-node-binding
subjects:
  - kind: ServiceAccount
    name: pd-csi-taint-webhook-sa
    namespace: gce-pd-csi-driver
roleRef:
  kind: ClusterRole
  name: pd-csi-taint-webhook-node-reader
  apiGroup: rbac.authorization.k8s.io