apiVersion: v1
kind: Service
metadata:
  name: pd-csi-taint-webhook
  namespace: gce-pd-csi-driver
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app: pd-csi-taint-webhook