kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restored-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-gce-pd
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: VolumeSnapshot
    name: snapshot-source-pvc
    apiGroup: snapshot.storage.k8s.io
