apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snapshot-source-pvc
spec:
  volumeSnapshotClassName: csi-gce-pd-snapshot-class
  source:
    persistentVolumeClaimName: source-pvc
