apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: "v5.1.0"

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-attacher
imageTag:
  name: registry.k8s.io/sig-storage/csi-attacher
  newTag: "v4.4.3"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resizer
imageTag:
  name: registry.k8s.io/sig-storage/csi-resizer
  newTag: "v1.12.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter
imageTag:
  name: registry.k8s.io/sig-storage/csi-snapshotter
  newTag: "v7.0.2"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.9.3"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # pdImagePlaceholder in test/k8s-integration/main.go is updated automatically with the newTag
  newName: gcr.io/samhalim-joonix/gcp-compute-persistent-disk-csi-driver
  newTag: "datacache_sam"
---
