apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: "v5.2.0"
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-attacher
imageTag:
  name: registry.k8s.io/sig-storage/csi-attacher
  newTag: "v4.8.1"
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resizer
imageTag:
  name: registry.k8s.io/sig-storage/csi-resizer
  newTag: "v1.13.2"
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter
imageTag:
  name: registry.k8s.io/sig-storage/csi-snapshotter
  newTag: "v8.2.1"
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.13.0"
---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # pdImagePlaceholder in test/k8s-integration/main.go is updated automatically with the newTag
  newName: us-central1-docker.pkg.dev/juliankatz-joonix/csi-dev/gcp-compute-persistent-disk-csi-driver
  newTag: "latest"
---

