apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../stable
- ./csi-driver.yaml
transformers:
- ../../images/prow-gke-release-staging-rc
patchesJson6902:
- path: increase-sidecar-operation-timeout.yaml
  target:
    group: apps
    kind: Deployment
    name: csi-gce-pd-controller
    version: v1
