apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/gke-release-staging/gcp-compute-persistent-disk-csi-driver
  newTag: "v0.5.1-rc1"
- name: gke.gcr.io/csi-provisioner
  newName: gcr.io/gke-release-staging/csi-provisioner
  newTag: "v1.2.0-gke.0"
- name: gke.gcr.io/csi-attacher
  newName: gcr.io/gke-release-staging/csi-attacher
  newTag: "v1.1.0-gke.0"
- name: gke.gcr.io/csi-node-driver-registrar
  newName: gcr.io/gke-release-staging/csi-node-driver-registrar
  newTag: "v1.1.0-gke.0"
