kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-controller
spec:
  serviceName: "csi-gce-pd"
  replicas: 1
  selector:
    matchLabels:
      app: gcp-compute-persistent-disk-csi-driver
  template:
    metadata:
      labels:
        app: gcp-compute-persistent-disk-csi-driver
    spec:
      serviceAccountName: csi-controller-sa
      containers:
        - name: csi-provisioner
          image: gke.gcr.io/csi-provisioner
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--feature-gates=Topology=true"
            - "--enable-leader-election=true"
            - "--leader-election-type=leases"
            - --leader-election-namespace=$(PDCSI_NAMESPACE)
          env:
          - name: PDCSI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: gke.gcr.io/csi-attacher
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--leader-election"
            - "--leader-election-type=leases"
            - --leader-election-namespace=$(PDCSI_NAMESPACE)
          env:
          - name: PDCSI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: gce-pd-driver
          # Don't change base image without changing pdImagePlaceholder in
          # test/k8s-integration/main.go
          image: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
          args:
            - "--v=5"
            - "--endpoint=unix:/csi/csi.sock"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/cloud-sa/cloud-sa.json"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: cloud-sa-volume
              readOnly: true
              mountPath: "/etc/cloud-sa"
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloud-sa-volume
          secret:
            secretName: cloud-sa
  # This is needed due to https://github.com/kubernetes-sigs/kustomize/issues/504
  volumeClaimTemplates: []
