apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver-alpha-win
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver-win
  newName: gcr.io/gke-release-staging/gcp-compute-persistent-disk-csi-driver
  newTag: "v1.0.1-gke.9"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-node-registrar-win
imageTag:
  name: gke.gcr.io/k8s-staging-csi/csi-node-driver-registrar-win
  newName: gcr.io/k8s-staging-csi/csi-node-driver-registrar
  newTag: "amd64-windows-canary"
