apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  gce-pd-csi-driver
resources:
- ../stable-master
patchesJson6902:
# disk_labels.yaml is used for testing and should not be merged to stable.
- target:
    group: apps
    version: v1
    kind: Deployment
    name: csi-gce-pd-controller
  path: disk_labels.yaml
- path: max-grpc-log-length.yaml
  target:
    group: apps
    kind: Deployment
    name: csi-gce-pd-controller
    version: v1
- path: default-fstype.yaml
  target:
    group: apps
    kind: Deployment
    name: csi-gce-pd-controller
    version: v1
- path: driver-args.yaml
  target:
    group: apps
    kind: Deployment
    name: csi-gce-pd-controller
    version: v1
transformers:
- ../../images/prow-stable-sidecar-rc-master
