kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      containers:
        - name: csi-driver-registrar
          image: gcr.io/gke-release-staging/csi-driver-registrar:latest
        - name: gce-pd-driver
          image: gcr.io/gke-release-staging/gcp-compute-persistent-disk-csi-driver:latest
