apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/gke-release-staging/gcp-compute-persistent-disk-csi-driver
  newTag: "latest"
- name: gke.gcr.io/csi-provisioner
  newName: quay.io/k8scsi/csi-provisioner
  newTag: "canary"
- name: gke.gcr.io/csi-attacher
  newName: quay.io/k8scsi/csi-attacher
  newTag: "canary"
- name: gke.gcr.io/csi-node-driver-registrar
  newName: quay.io/k8scsi/csi-node-driver-registrar
  newTag: "canary"
- name: gke.gcr.io/csi-resizer
  newName: quay.io/k8scsi/csi-resizer
  newTag: "canary"
- name: gke.gcr.io/csi-snapshotter
  newName: quay.io/k8scsi/csi-snapshotter
  newTag: "canary"
